import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Generative from '../components/Generative'
import AuthButton from "../components/auth/AuthButton";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<AuthButton/>
				<Generative />
			</main>
		</div>
	)
}
